name: LaberintoMobs
version: 1.4.0
main: com.laberinto.LaberintoMobs
api-version: '26.1'
description: Mobs agresivos y botin aleatorio dentro de una zona (laberinto).
commands:
  laberinto:
    description: Configura la zona del laberinto
    usage: /laberinto <pos1|pos2|info|limpiar|dificultad|loot|reload>
    permission: laberinto.admin
  nivel:
    description: Muestra la dificultad actual del laberinto
    usage: /nivel
permissions:
  laberinto.admin:
    default: op
